/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\Models\v2\chairs_2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chairs_2 (props) {
  const { nodes, materials } = useGLTF('./Models/v2/chairs_2.gltf')

  

  return (
    <group {...props} dispose={null} scale={[0.1, 0.1, 0.1]}>
      <mesh geometry={nodes.classic_Arm.geometry} material={materials.chair} visible={false}/>
      <mesh geometry={nodes.classic_Back.geometry} material={materials.chair} visible={false}/>
      <mesh geometry={nodes.classic_Cushion.geometry} material={materials.chair} visible={false}/>
      <mesh geometry={nodes.classic_Seat.geometry} material={materials.chair} visible={false}/>
      <mesh geometry={nodes.classic_Legs.geometry} material={materials.chair} visible={false}/>
      <mesh geometry={nodes.mdr_Arm.geometry} material={materials.chair} />
      <mesh geometry={nodes.mdr_Back.geometry} material={materials.chair} />
      <mesh geometry={nodes.mdr_Cushion.geometry} material={materials.chair} />
      <mesh geometry={nodes.mdr_Legs.geometry} material={materials.chair} />
      <mesh geometry={nodes.mdr_Seat.geometry} material={materials.chair} />
    </group>
  )
}

useGLTF.preload('./Models/v2/chairs_2.gltf')
